In [1]:
import numpy as np

In [21]:
a = np.array([[0, 1, 2]])

a = np.append(a, np.array([[1, 2, 3]]))
a = np.append(a, np.array([[1, 2, 3]]))
a = np.append(a, np.array([[1, 2, 3]]))
a = a.reshape(-1, 3)

np.append(a, np.array([1, 2, 3]))
print(a)
# np.append()

[[0 1 2]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# reshape the lookup array into a column vector
lookup_array_column = lookup_array.reshape(-1, 1)

# find the index of the closest value in the lookup array for each value in the input array
indices = np.abs(input_array[..., np.newaxis] - lookup_array_column).argmin(axis=-1)
